# Custom Language File for Launcher Customizer

[ejs.app]
title = "FyrethCraft MC Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/j-tap/VR9-HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/EYUbgjD2"

[ejs.settings]
sourceGithubLink = "https://github.com/j-tap/VR9-HeliosLauncher"
supportLink = "https://github.com/j-tap/VR9-HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO FyrethCraft"
welcomeDescription = "FyrethCraft is a modded Minecraft server that is hosted on the FyrethCraft network. We are a community of players who are dedicated to creating a fun and immersive experience for everyone."
welcomeDescCTA = "You are just a few clicks away from FyrethCraft."
